#!/bin/bash

#creates and activtes python virtual environment
python3 -m venv myvenv
myvenv/Scripts/Activate.ps1

#installs dependencies
python -m pip install pymongo
pip install Flask
pip install requests
